### ISSUE TITLE
Xcode Version

### ISSUE THREAD

**Issue by fluffysamoyed359** [DePasqualeOrg/Flux-Demo#1]
Which Xcode version did you use to make this app? When I try to open it in my Xcode, I get this error

"cannot be opened because it is in a future Xcode project file format. Adjust the project format using a compatible version of Xcode to allow it to be opened by this version of Xcode."

**Comment by DePasqualeOrg** [comment]
I'm using Xcode 16.1, and I don't get this message when I open the project.
